trigger:
  - main

pool:
  name: vm-sai-devops

stages:
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: BuildJob
    displayName: "Build Job"
    pool:
      name: build-env
    steps:
    - script: echo "Building the project..."
      displayName: "Build Step"

- stage: Test
  displayName: "Test Stage"
  dependsOn: Build
  jobs:
  - job: TestJob
    displayName: "Test Job"
    pool:
      name: build-env
    steps:
    - script: echo "Running tests..."
      displayName: "Test Step"

- stage: Deploy
  displayName: "Deploy Stage"
  dependsOn: Test
  jobs:
  - job: DeployJob
    displayName: "Deploy Job"
    pool:
      name: build-env
    steps:
    - script: echo "Deploying the application..."
      displayName: "Deploy Step"
